services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: todo-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperStrongPassword123!
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:                        